main:
  - name: 关于我
    url: '#about'
    weight: 1
  - name: 文章
    url: /posts/
    weight: 2
  - name: 日常
    url: /docs/
    weight: 3
  - name: 其他
    url: /blank
    weight: 4
  - name: 查询
    url: /search
    weight: 5
  - name: 统计
    url: /stats
    weight: 6